function doTheClickThing() {
    document.body.style.color = getRandomThing(fgcolors);
    document.body.style.backgroundColor = getRandomThing(bgcolors);
    document.getElementById("icebreaker").innerHTML = '<p>'+getRandomThing(questions)+'</p>';
}

function getRandomThing(thing) {
    return thing[Math.floor(Math.random()*thing.length)];
}

const fgcolors = [
    "#f4f990",
    "#cdf199",
    "#eea672",
    "#ee7294",
    "#7297ee",
    "#72eed8",
    "#eeac72"
]

const bgcolors = [
    "#2c2c38",
    "#382c33",
    "#2d2c38",
    "#2c3538",
    "#2c3832",
    "#31382c",
    "#38332c"
]

const questions = [
    "Someone offers you a billion dollars to lose one of your 5 senses. Would you do it? If so, which one?",
    "The zombie apocalypse is coming, who are 3 people you want on your team?",
    "What is your most used emoji?",
    "What was the worst style choice you ever made?",
    "What was the worst haircut you ever had?",
    "Who was your childhood actor/actress crush?",
    "If you were a wrestler what would be your entrance theme song?",
    "Have you ever been told you look like someone famous, who was it?",
    "If you could bring back any fashion trend what would it be?",
    "What's the most embarrassing fashion trend you used to rock?",
    "What did you name your first car?",
    "Does your current car have a name? What is it?",
    "You have your own late night talk show, who do you invite as your first guest?",
    "If a movie was made of your life what genre would it be, who would play you?",
    "If you were famous, what would you be famous for?",
    "You have to sing karaoke, what song do you pick?",
    "What was your least favorite food as a child? Do you still hate it or do you love it now?",
    "If you had to eat one meal everyday for the rest of your life what would it be?",
    "If you were left on a deserted island with either your worst enemy or no one, which would you choose? Why?",
    "If aliens landed on earth tomorrow and offered to take you home with them, would you go?",
    "60s, 70s, 80s, 90s: Which decade do you love the most and why?",
    "What's your favorite sandwich and why?",
    "What's the best piece of advice you've ever been given?",
    "When you die, what do you want to be remembered for?",
    "What is your favorite item you've bought this year?",
    "What would be the most surprising scientific discovery imaginable?",
    "What is your absolute dream job?",
    "What would your talent be if you were Miss or Mister World?",
    "What would the title of your autobiography be?",
    "Say you're independently wealthy and don't have to work, what would you do with your time?",
    "If you had to delete all but 3 apps from your smartphone, which ones would you keep?",
    "What is your favorite magical or mythological animal?",
    "What does your favorite shirt look like?",
    "Who is your favorite Disney hero or heroine? Would you trade places with them?",
    "What would your dream house be like?",
    "If you could add anyone to Mount Rushmore who would it be; why?",
    "You're going to sail around the world, what's the name of your boat?",
    "What fictional family would you be a member of?",
    "What is your favorite television network?",
    "What sport would you compete in if you were in the Olympics?",
    "What was the worst job you ever had?",
    "You can have anyone fictional as your imaginary friend, who do you choose and why?",
    "What would your superpower be and why?",
    "Which band / artist -- dead or alive would play at your funeral?",
    "As a child, what did you want to be when you grew up?",
    "What's your favorite tradition or holiday?",
    "What fictional world or place would you like to visit?",
    "What is your favorite breakfast food?",
    "What is your favorite time of the day and why?",
    "Coffee or tea?",
    "Teleportation or flying?",
    "What is your favorite TV show?",
    "What book, movie read/seen recently you would recommend and why?",
    "What breed of dog would you be?",
    "If you had a time machine, would go back in time or into the future?",
    "Do you think you could live without your smartphone (or other technology item) for 24 hours?",
    "What is your favorite dessert?",
    "What was your favorite game to play as a child?",
    "Are you a traveler or a homebody?",
    "What's one career you wish you could have?",
    "What's your favorite place of all the places you've travelled?",
    "Have you ever met your idol or someone you revere greatly?",
    "Have you ever completed anything on your \"bucket list\"?",
    "Do you have a favorite plant?",
    "What did you have for breakfast this morning?",
    "What was the country you last visited outside of United States?",
    "What's is one thing we don't know about you?",
    "What is your favorite meal to cook and why?",
    "Are you a morning person or a night person?",
    "What is your favorite musical instrument and why?",
    "Are you a cat person or a dog person?",
    "What languages do you know how to speak?",
    "Popcorn or M&Ms?",
    "What's the weirdest food you've ever eaten?",
    "What's the most out-of-character thing you've ever done?",
    "What is your cellphone wallpaper?",
    "You can have an unlimited supply of one thing for the rest of your life, what is it?",
    "What's your best scar story?",
    "Would you go with aliens if they beamed down to Earth?",
    "Are you sunrise, daylight, twilight, or nighttime? Why?",
    "What season would you be?",
    "Are you a good dancer?",
    "What fruit or vegetable would you most want to be?",
    "If you could hang out with any cartoon character, who would you choose and why?",
    "If you could live anywhere in the world for a year, where would it be?",
    "If you could commit any crime and get away with it what would you choose and why?",
    "If you could choose any person from history to be your imaginary friend, who would it be and why?",
    "If you could see one movie again for the first time, what would it be and why?",
    "If you could live in any country, where would you live?",
    "If you could choose any two famous people to have dinner with who would they be?",
    "If you could be any animal in the world, what animal would you choose to be?",
    "If you could do anything in the world as your career, what would you do?",
    "If you could be any supernatural creature, what would you be and why?",
    "If you could change places with anyone in the world, who would it be and why?",
    "If you could rename yourself, what name would you pick?",
    "If you could have someone follow you around all the time, like a personal assistant, what would you have them do?",
    "If you could instantly become an expert in something, what would it be?",
    "If you could be guaranteed one thing in life (besides money), what would it be?",
    "If you had to teach a class on one thing, what would you teach?",
    "If you could magically become fluent in any language, what would it be?",
    "If you could be immortal, what age would you choose to stop aging at and why?",
    "If you could be on a reality TV show, which one would you choose and why?",
    "If you could eliminate one thing from your daily routine, what would it be and why?",
    "If you could go to Mars, would you? Why or why not?",
    "If you could have the power of teleportation right now, where would you go and why?",
    "If you could write a book that was guaranteed to be a best seller, what would you write?",
    "Would you rather live in the ocean or on the moon?",
    "Would you rather meet your travel back in time to meet your ancestors or to the future to meet your descendants?",
    "Would you rather lose all of your money or all of your pictures?",
    "Would you rather have invisibility or flight?",
    "Would you rather live where it only snows or the temperature never falls below 100 degrees?",
    "Would you rather always be slightly late or super early?",
    "Would you rather give up your smartphone or your computer?",
    "Would you rather live without heat and AC or live without social media?",
    "Would you rather be the funniest or smartest person in the room?",
    "Would you rather be able to run at 100 miles per hour or fly at 10 miles per hour?",
    "Would you rather be a superhero or the world's best chef?",
    "Would you rather be an Olympic gold medallist or an astronaut?",
    "If you could add a word to the dictionary what would you add and what would it mean?",
    "What clothing item would make you walk out on a date if someone wore it?",
    "The zombie apocalypse is coming, who are three people you want on your team?",
    "If you could choose your age forever, what age would you choose and why?",
    "If you were to change your name, what name would you change to and why?",
    "If you could meet any living person for dinner, who would you pick and why?",
    "Cats or dogs?",
    "Would you rather be invisible or be able to read minds?",
    "If you could be an animal, what animal would you be and why?",
    "What's your best scary story?",
    "If you had 25 hours a day, how would you use your extra time?",
    "How would you spend a million dollars? How about a billion?",
    "If you could kill any fashion trend forever what would it be?",
    "If you had to delete all but three apps from your smartphone, which ones would you keep?",
    "What skill do you think everyone should have?",
    "If you were a vegetable, what vegetable would you be and why?",
    "If you had to eat one meal every day for the rest of your life what would it be?",
    "How do you like your eggs?",
    "What are your three favorite foods?",
    "What are your three favorite drinks?",
    "What's your favorite breakfast cereal?",
    "If you could be in any movie, what would it be and what character would you play?",
    "Which actor would you want to play you in the movie about your life?",
    "If you were a superhero what would your name be?",
    "If you were a superhero what would your superpower be and why?",
    "What are you reading right now?",
    "What book did you read that changed your life the most?",
    "What movie have you seen recently that you would recommend and why?",
    "What is your favorite sport to watch and why?",
    "If you had to play one album forever which one would it be?",
    "Which song can you listen to all day long?",
    "If you were famous what would you be famous for?",
    "What would you do with your \"15 minutes of fame\"?",
    "If you could be any sports personality who would it be and why?",
    "What's the best piece of advice you have ever been given?",
    "If you could change one thing about yourself what would you choose?",
    "If you could pick up a new skill in an instant what would it be?",
    "What's the best advice you've ever heard?",
    "If you were independently wealthy and didn't have to work, what would you do with your time?",
    "How would your friends describe you?",
    "What would you like to be known/remembered for?",
    "Do you collect anything?",
    "What would you like to do when you retire?",
    "What is the best perk you have ever enjoyed at a job?",
    "What's your favorite color and how does that color make you feel?",
    "If you could live anywhere on this planet, where would you choose to live?",
    "If extraterrestrials landed on earth and offered to take you with them, would you go?",
    "If you were stranded on a desert island, what three items would you want to have with you?",
    "What's your favorite place you've ever visited?",
    "What is your favorite season of the year and why?",
    "What is your favorite holiday and why?",
    "If you could meet any historical figure, who would you choose and why?",
    "What is the meaning of your name?",
    "What was the first thing you bought with your own money?",
    "What's your favorite family tradition?",
    "Who had the most influence on you growing up?",
    "What's your earliest memory?",
    "If you had to lose all your memories which one would want to lose last?",
    "If you could choose any historical figure to be your imaginary friend, who would it be and why?",
    "What are your favorite songs from your teenage years that you still rock out to when nobody else is listening?",
    "What's your most embarrassing moment from your teen years?",
    "What's the craziest dare you ever took?",
    "What's the grossest food you ever had to eat to be polite?",
    "What's the worst thing you ever did as a kid -- and got away with?",
    "What's the craziest fashion trend you ever rocked?",
    "What did you get into the most trouble for with your parents as a kid?",
    "What's your silliest memory with your best friend?",
    "What part of elementary school do you wish you could incorporate into your adult life? (i.e. naptime)",
    "What was the first concert you ever went to?",
    "Do you have any crazy roommate stories?",
    "What is the weirdest thing you've ever eaten for breakfast that is not a breakfast food?",
    "What's the strangest family tradition in your family?",
    "What was your favorite item of clothing as a kid?",
    "What Disney/cartoon character were you inexplicably afraid of as a kid?",
    "What was your first record, tape or CD that you ever owned?",
    "What were words you couldn't pronounce as a child, so you made up your own?",
    "Have you ever gotten super lost? What happened?",
    "What's the story of your first crush?",
    "What was your first job? What did you like/dislike about it?",
    "Who was the worst grade-school teacher you ever had?",
    "What afterschool activity did you quit as a kid, and why?",
    "What's the funniest thing that ever happened on your family vacation?",
    "What's the funniest animal you've ever owned as a pet?",
    "What's the worst haircut you ever had?",
    "What's the best prank you've ever played on someone?",
    "What's the most ridiculous thing your parents ever did to embarrass you?",
    "As a kid, did you ever do something wrong but manage to pin it on your siblings?",
    "What's the worst job you've ever had?",
    "What totally rad expression did you overuse in high school?",
    "What was your favorite Halloween costume you wore as a child?",
    "Who is your craziest/most interesting relative?",
    "What band would you be embarrassed to admit you listen to?",
    "What's the craziest thing on your bucket list?",
    "What's a weird fact you happen to know?",
    "What is your real favorite movie, and what movie do you pretend is your favorite to sound cultured?",
    "What's your strangest talent?",
    "What's your funniest talent? Or un-talent?",
    "What's your best idea for a reality TV show?",
    "Which Disney character's story does your life most resemble?",
    "Everyone has those recurring bad dreams... what is your nightmare?",
    "What are two truths and a lie about you?",
    "What's your favorite part of a county fair?",
    "What show on Netflix did you binge watch embarrassingly fast?",
    "Which celebrity do you shamelessly follow in the news?",
    "What's something about you that people would be surprised to know?",
    "What is your favorite smell and why?",
    "What's the best knock-knock joke you know?",
    "What completely safe animal are you inexplicably afraid of?",
    "What food could you not live without?",
    "What dance move are you secretly awesome at?",
    "What commercial jingle gets stuck in your head all the time?",
    "What sport did you try as a child and fail at?",
    "What interesting skill do you want to learn?",
    "What's the most random thing in your purse/wallet?",
    "What invention do you think will be popular in 20 years?",
    "What blog or website are you embarrassed to admit you love?",
    "What do you never leave the house without (can't be your phone, keys or wallet)?",
    "Who is your celebrity look-alike?",
    "What's your favorite book? Why?",
    "What do you pretend to hate but actually love?",
    "What's a nickname people actually call you?",
    "If you could pick your nickname, what would people call you?",
    "Have you ever lied about an interest/talent to impress someone? What happened next?",
    "If you had a boat, what would you name it?",
    "If you could pick a TV show to be your life, what show would it be?",
    "If your best friend picked a tattoo for you to get, what would he/she pick?",
    "If you could only eat at one restaurant forever, what restaurant would it be?",
    "If you could only wear one type of shoes for the rest of your life, what type of shoes would it be?",
    "If you could have any celebrity be your best friend, which celebrity would you pick?",
    "If you created your own country, what would it be called?",
    "If all your clothes had to be one color forever, what color would you pick?",
    "If you had to be an animal, which animal would you be?",
    "If you had lots of money, what unnecessary thing would you splurge on (i.e. a private plane, concert tickets)?",
    "If you could switch places with anyone in your family for a day, who would it be?",
    "If you wrote a book, what would it be called?",
    "If you had to use a fake name, what fake name would you make up?",
    "If you could live any historical figure's life, which one would you choose?",
    "If you could eliminate one food so that no one would eat it ever again, what would you pick to destroy?",
    "If you had to wear a hat every day for the rest of your life, what type of hat would it be?",
    "If you could create one holiday, what would you create?",
    "If you were a vegetable, what would you be?",
    "If you were an Olympic athlete, what sport would you compete in?",
    "If you were the president, what would you change about the decorations in the White House?",
    "If you were a type of jeans, what type would you be?",
    "If you could be one superhero, which superhero would you be?",
    "If you could turn the ocean into a liquid other than water, which one would you pick?",
    "If you had to be Siamese twins with one person, which person would you pick to be stuck with?",
    "If you could pick three famous people to be a part of your entourage, who would you pick?",
    "If you could only listen to one song for the rest of your life, which song would you pick?",
    "Which celebrity would you pick to exchange lives with?",
    "If you could pick one job to do forever (and be guaranteed all the money you need), what job would it be?",
    "If you were trying out for a singing reality show, what song would you sing?",
    "What game show would you be super awesome at?",
    "If you had to endorse a brand, which brand would it be?",
    "If you could have an endless supply of any food, what would you get?",
    "If you were an animal, what would you be and why?",
    "What is one goal you'd like to accomplish during your lifetime?",
    "When you were little, who was your favorite super hero and why?",
    "Who is your hero? (a parent, a celebrity, an influential person in one's life)",
    "What's your favorite thing to do in the summer?",
    "If they made a movie of your life, what would it be about and which actor would you want to play you?",
    "If you were an ice cream flavor, which one would you be and why?",
    "What's your favorite cartoon character, and why?",
    "If you could visit any place in the world, where would you choose to go and why",
    "What's the ideal dream job for you?",
    "Are you a morning or night person?",
    "What are your favorite hobbies?",
    "What are your pet peeves or interesting things about you that you dislike?",
    "What's the weirdest thing you've ever eaten?",
    "Name one of your favorite things about someone in your family.",
    "Tell us about a unique or quirky habit of yours.",
    "If you had to describe yourself using three words, it would be...",
    "If someone made a movie of your life would it be a drama, a comedy, a romantic-comedy, action film, or science fiction?",
    "What's the best trip (traveling wise) you ever had?",
    "What's your favorite thing about the place where you live?",
    "Where is your favorite vacation spot?",
    "What's your favorite seat on an airplane?",
    "Have you ever been on a cruise? Where did you go?",
    "Do you enjoy the outdoors? What's your favorite outdoor activity?",
    "How many countries have you visited outside your own?",
    "What is your favorite weekend trip?",
    "Who is your favorite person to travel with?",
    "What is your favorite theme park?",
    "In your opinion, what is the most beautiful place on earth?",
    "Beach, safari, or forest vacation?",
    "Do you have any pets? What are their names?",
    "What is your spirit animal?",
    "What is your favorite animal?",
    "What is your favorite magical or mythological creature?",
    "What famous animal movie character do you like the most?",
    "Did you have a stuffed animal as a child? What was its name?",
    "Are there any specific animals you are afraid of? Why?",
    "What is the funniest thing one of your pets have done?",
    "What is your favorite zoo animal?",
    "If you were a fish, what type would you be?",
    "If you had your human body, but the head of an animal, what animal would you pick?",
    "Favorite grocery item while shopping locally?",
    "What is your favorite restaurant?",
    "If you could only eat one item of food for the rest of your life, what would you eat?",
    "What is your favorite candy or treat?",
    "Sweet, salty, or sour?",
    "What is something you are great at cooking?",
    "What is something you can't cook?",
    "If you could eliminate one food so no one could eat it ever again, what would you destroy?",
    "What is your favorite breakfast? Lunch? Dinner?",
    "What is your favorite hobby?",
    "What is your favorite thing to do by yourself?",
    "What is your favorite sport or physical activity?",
    "What crazy activities do you dream of trying someday?",
    "What is your idea of fun?",
    "What two things do you consider yourself to be very good at?",
    "What two things do you consider yourself to be very bad at?",
    "If money and time were no object, what would you be doing right now?",
    "What is something you hate doing? Why?",
    "What is something you love doing? Why?",
    "Do you have any hidden talents? What can you do?",
    "What was one new experience you tried that was completely unknown or uncomfortable to you at the time you tried it?",
    "Have you ever been out of the country?",
    "Have you ever ridden on a motorcycle?",
    "Have you ever lived in another state?",
    "Have you ever met a celebrity?",
    "Have you ever been to Disney Land or Disney World?",
    "Have you ever planted a garden?",
    "Have you ever experienced a natural disaster like a hurricane or tornado?",
    "Have you ever won a contest?",
    "Have you ever done any extreme sports like skydiving or bungee jumping?",
    "When did you get your first cell phone? What kind was it?",
    "If you had to choose between only having a cell phone or a car for the rest of your life, which would you choose?",
    "How many Facebook friends do you have? How many of them do you actually communicate with?",
    "What technology innovation made the most impact on your life?",
    "Desktop, laptop, or tablet? Which do you prefer to use?",
    "What is your favorite thing about technology? Least favorite?",
    "Where would you time-travel, if it were possible?",
    "If you could have a superpower, what would it be and why?",
    "If you were the captain of a pirate ship, what would be the name of your ship?",
    "If you could travel to any other planet (real or fictional), where would you go and why?",
    "What is your favorite movie?",
    "Who is your favorite actor/actress?",
    "What is your favorite book?",
    "What is your favorite tv series?",
    "If you could be any fictional character, who would you be?",
    "What type of music do you listen to?",
    "What movie can you rewatch over and over again?",
    "If you could go back in time and make little changes to your childhood, what is one thing you'd learn and master over the years so you'd be an expert at it today?",
    "If you won a lottery of $1 billion, what would you do with all the money?",
    "How would you change your life today if the average life expectancy was 400 years?",
    "What is the most challenging job you can think of?",
    "A genie grants you three wishes but none of them can directly benefit you. What would those wishes be?",
    "If you had to change your name, what would your new name be, and why would you choose that name?",
    "What are the best and worst purchases you've ever made?",
    "What is your biggest pet peeve?",
    "What is your most treasured material possession?",
    "What do you never leave the house without other than your phone, keys or wallet?",
    "Who is your hero, and why?",
    "What is your earliest childhood memory?",
    "Who was your favorite teacher in school and how did he or she impact you?",
    "If you could choose an age to remain forever, which age would you choose?",
    "What is one important skill every person should have?",
    "What was the best thing that happened to you this weekend? This month? This year?",
    "What is your favorite holiday?",
    "Do you set New Years Resolutions? What was one of yours this year? Have you kept it?",
    "What are you going to do when you retire?",
    "There are now 25 hours in a day! How do you spend your extra hour?",
    "What \"old person\" things do you do?",
    "How long would you last in a zombie apocalypse?",
    "Who is your favorite cartoon character?",
    "What is your guilty pleasure?",
    "If you were a vegetable, what vegetable would you be?",
    "If you woke up tomorrow as an animal, what animal would you choose to be and why?",
    "If you could live anywhere on this planet and take everything that you love with you, where would you choose to live?",
    "What favorite color are you and how does being that color make you feel?",
    "If you could choose an imaginary friend, who would you choose and why?",
    "If you could sit on a bench in a beautiful woods, who would you like sitting next to you on the bench and why?",
    "Are you sunrise, daylight, twilight, or night? Please share why you picked your time of day.",
    "If you could be in the movie of your choice, what movie would you choose and what character would you play? Why?",
    "If you were a city, which city would you choose to be and why?",
    "If you were a candy bar, which candy bar would you be? Share why.",
    "If you were to change your name, what name would you adopt going forward? Why?",
    "Are you spring, summer, fall, or winter? Please share why.",
    "Share a description of your favorite material object that you already own?",
    "What item that you don't have already, would you most like to own?",
    "If you could only choose one vacation destination where would you pick and why?",
    "If you were to create a slogan for your life, what would the slogan be?",
    "Pick something out of your pocket or purse and share with the group why it's important to you.",
    "If you could meet any living person for a chat over a shared dinner, who would you pick and why?",
    "If you awoke one day as a flower, what flower would you choose to be?",
    "If you could choose one hobby that now seems out of your reach either financially or time-wise, what hobby would you take up and why?",
    "Thinking about the architecture of houses, what type of architecture is the best fit for you? What appeals to you about your choice?",
    "What's the best thing you've got going on in your life at the moment?",
    "What scene in a movie always gives you goosebumps every time you watch it?",
    "What incredibly common thing have you never done?",
    "What topic could you give a 20 minute presentation on without any preparation?",
    "What are some of your favorite games to play?",
    "What takes a lot of time but is totally worth it?",
    "What is the most amazing fact you know?",
    "What website or app doesn't exist, but you really wish it did?",
    "What's your favorite type of day? (weather, temp, etc.)",
    "What is the most clever or funniest use of advertising you've seen?",
    "How into self-improvement are you?",
    "Are you more productive at night or in the morning? Do you think it's possible to change and get used to another schedule?",
    "What has taken you the longest to get good or decent at?",
    "What food do you love that a lot of people might find a little odd?",
    "If you could start a charity, what would it be for?",
    "What was the funniest thing you've seen recently online?",
    "What's something that a lot of people are missing out on because they don't know about it?",
    "What are some of your guilty pleasures?",
    "Who is the most interesting person you've met and talked with?",
    "What has really taken a toll on you?",
    "How did you spend the money from your very first job?",
    "What do you wish someone taught you a long time ago?",
    "Do you think you rely too heavily on your phone? Why or why not?",
    "How could carousels be spiced up so they are more exciting?",
    "What's your favorite car that you've owned?",
    "What subjects should be taught in school but aren't?",
    "What's the biggest vehicle you've driven?",
    "What songs would be played on a loop in hell?",
    "What rule do you wish they would introduce into your favorite sport?",
    "What kind of challenges are you facing these days?",
    "What do you highly recommend to most people you meet?",
    "Do you think you have a pretty good work-life balance? Why or why not?",
    "What was the last thing you were really excited about?",
    "What's your best \"my coworkers are crazy\" story?",
    "What does your perfect breakfast look like?",
    "What are some of your favorite holiday traditions that you did while growing up?",
    "If you could choose your dreams, what would you prefer to dream about?",
    "Would you ride in a zeppelin if given a chance?",
    "What's something that was once important but is now becoming less and less relevant?",
    "What tells you the most about a person?",
    "When is the most interesting period in history?",
    "What is the best pair of shoes you have owned?",
    "What book had the most significant impact on you?",
    "Where's your favorite place to nap?",
    "What is the best event you've attended?",
    "What do you buy way more of than most people?",
    "What do you rebel against?",
    "What well-known person does the most good for the world?",
    "What's your favorite food combination?",
    "What's the weirdest way you have met someone?",
    "What's the most amazing natural occurrence you've witnessed?",
    "How did you get that scar of yours?",
    "What do you wish was illegal?",
    "If someone came up to you and said \"Hey, do that thing you do!\", what thing would pop into your head first?",
    "Who is the most intelligent or creative person you know?",
    "What wastes the most time in your day to day life?",
    "What's a problem you have, that might be entirely unique to you?",
    "What company or brand did you love until they betrayed your trust?",
    "Would you ever try space tourism, if you had the money for it?",
    "What's the most annoying machine you must deal with regularly?",
    "What are you grateful for?",
    "What hobby would you be a lot of fun to get into?",
    "What do you resent paying for most?",
    "What pets did you have growing up?",
    "What's the best or worst prank you've played on someone?",
    "What was the scariest movie you've seen?",
    "What motivates you?",
    "Where are three places you really want to visit before you die?",
    "What's the best location to fully enjoy a good cup of coffee?",
    "How handy are you when it comes to fixing things?",
    "What skill or talent would you most like to learn?",
    "What weird thing do you have nostalgia for?",
    "What works of art have really made an impression on you?",
    "What culture would you like to learn more about?",
    "If you were featured on the local news, what would you most likely be on there for?",
    "What do you wish your phone could do?",
    "What's your favorite international food?",
    "What workers have the worst jobs?",
    "What kind of physical activities do you like doing?",
    "Would you rather watch a movie on your TV at home or on the big screen in the theater, and why?",
    "What assumption you made went hilariously wrong?",
    "What big problem do you think technology will solve next?",
    "What fashion trend needs to be brought back?",
    "How do you think you will be/act when you are old?",
    "What's your favorite way to waste time online?",
    "What's the longest trip you've been on?",
    "What was something you thought would be easy until you tried it?",
    "What, in your opinion, is the most amazing animal?",
    "Who is the oldest person you know personally? What interesting stories have they told you?",
    "Who is the funniest person in your family?",
    "What useless facts do you know?",
    "What's your favorite Olympic sport to watch?",
    "How do you usually get your news?",
    "What smell do you hate that doesn't seem to bother other people?",
    "What's the most delightful hotel or house you've stayed in on vacation?",
    "What weird quirks did you pick up from your parents?",
    "What were your favorite television shows when you were growing up?",
    "What's the silliest thing you are pretty good at?",
    "What's your idea of a great day?",
    "What do you want to do when you retire?",
    "What do you do to unwind after a hard day?",
    "Who is the most competitive person you know?",
    "Would you rather spend time with other people or at home alone?",
    "What are some films that would make it on to your top 50 list of movies?",
    "What slang are you really happy went out of fashion?",
    "What music do you put on when you want to get pumped?",
    "What makes you feel old when you think about it?",
    "How well do you know your neighbors?",
    "What's the best backhanded compliment you've heard / can think of on the spot?",
    "Who is the most interesting stranger you've met?",
    "What was your funniest or worst experience with a dentist?",
    "What's the noblest endeavor a person can dedicate their life to?",
    "What's your idea of a great party?",
    "What are some of your favorite scenes from movies?",
    "What are two of your favorite snacks?",
    "What's the biggest adventure you've been on?",
    "Besides war and diplomacy, what would be the best way for countries to settle disputes?",
    "What household chore do you actually enjoy?",
    "What is something you do better than most people and something you do worse than most people?",
    "What TV show are you hooked on or were recently hooked on?",
    "If you had to lose one of your senses, which would you choose to lose?",
    "If a new volcano formed and the government had an online contest to see what it would be named, what name would you submit?",
    "What is the last goal you achieved?",
    "What was your worst haircut experience?",
    "Do you prefer pens or pencils? Why?",
    "What's the best way to stay young?",
    "What is the most stressful TV show or movie you watched?",
    "How good are you at drawing?",
    "What did your teachers and parents say would be really important when you grew up, but it hasn't been? ",
    "How do you feel about clowns?",
    "What is your favorite genre of movie? Why?",
    "What brands do you love/hate the most?",
    "What is the weirdest food combination you've made and tried?",
    "What would you change if you were in charge of the company you work for?",
    "Who has been your most interesting/confusing/annoying neighbor?",
    "Has there ever been a time when something so amazing or unexpected happened that it literally left you speechless for a time?",
    "Where's the most surreal area you been to?",
    "What are common misconceptions about your job?",
    "What public spaces do you feel most comfortable in? (Library, bar, park, mall, stadium, etc.)",
    "What's the most outdated piece of tech you still use regularly?",
    "What's the weirdest food you've eaten?",
    "Who was your favorite teacher?",
    "What recent trend are you totally on board with?",
    "What about becoming an adult caught you completely off guard?",
    "How often do you dance?",
    "What's the best cake you've ever eaten?",
    "What kind of art do you appreciate the most?",
    "What crossed way too far into the uncanny valley for you?",
    "What's your favorite thing about the area/city/state you live in?",
    "What's the best day you've had recently?",
    "What's your favorite way to spend time outdoors?",
    "What does your perfect burger or sandwich have in it?",
    "What's the worst advice you've been given?",
    "What's the strangest name someone you have met had?",
    "What was something courageous you've (in person) seen someone do?",
    "What card or board games do you like to play?",
    "What are you best at fixing?",
    "What movie never gets old no matter how many times you've seen it?",
    "If the universe is just a simulation, what update or patch does it need?",
    "What's the scariest horror movie or horror book monster?",
    "What's the most unique shop or restaurant you've been in?",
    "What hard time in your life left you a better person after it was finished?",
    "What's the best sports game you've been to?",
    "What period would be the best to be born in?",
    "What sport do you wish you knew more about?",
    "What's something you're looking forward to?",
    "What's the most creative thing you've done?",
    "What are you hilariously bad at?",
    "Tell me about a time you were totally out of your element/comfort zone.",
    "Are you a cat or dog person or neither? Why?",
    "Who is the most gifted person you know?",
    "What was your best vacation?",
    "What do you usually do on your commute to work?",
    "What was the craziest theme park or fair ride you've been on?",
    "What kind of people do you most enjoy hanging out with?",
    "What do you think the ideal age to be is?",
    "What are you kind of snobby about?",
    "What toy did you hate most as a child?",
    "What's your drink of choice? (Either alcoholic or non.)",
    "If you left your current life behind and ran away to follow your dreams, what would you be doing?",
    "What food is underrated or underappreciated?",
    "What's your favorite line from a book or a movie?",
    "What is the best thing you have ever bought?",
    "What catchy jingle or bit of advertising has stuck with you all these years?",
    "What luxury is totally worth the price?",
    "What is the most unique or silliest problem you have going on in your life at the moment?",
    "What could movie theaters do to improve the experience of going there?",
    "If you were so wealthy you didn't need to work, what would you do with your time?",
    "What apps do you use most?",
    "What is the most tedious and/or the most exciting sport to watch?",
    "What's your favorite island that you've visited?",
    "What do you geek out about?",
    "Besides insects and spiders, what animals annoy you the most?",
    "What's your favorite month?",
    "What's the best concert you've been to and why was it so good?"
]